### ISSUE TITLE
Doeltemperatuur does not follow Stooklijn watertemp target

### ISSUE THREAD

**Issue by PvdGulik** [altrnate32/esp-lg-control#15]
Using your latest version, found that "Doeltemperatuur" is not following the changing "Stooklijn watertemp target".
I think the "Doeltemperatuur" should follow the "Stooklijn watertemp target". How would the AWHP know to change the target..
Now I'm changing the "Doeltemperatuur" manual, to follow the "Stooklijn watertemp target"

Settings stooklijn
<img width="389" alt="Scherm­afbeelding 2023-11-22 om 12 34 02" src="https://github.com/altrnate32/esp-lg-control/assets/9421474/bf4012b2-6273-4a2c-a994-2049d8fbbb58">

Difference between "Doeltemperatuur" and "Stooklijn watertemp target" after long wait..
<img width="395" alt="Scherm­afbeelding 2023-11-22 om 12 34 14" src="https://github.com/altrnate32/esp-lg-control/assets/9421474/0b58629b-c4c7-4b98-8d87-a088978eb0d9">

**Comment by altrnate32** [comment]
Based on only these values I have no way to troubleshoot.
Please include at least controller state and controller info. There are several reasons why the two values could be different.

**Comment by PvdGulik** [comment]
Hereby the extra info. I would expect that when I adjust e.g. the "Stooklijn Offset" with 3, after a few seconds the "Stooklijn Watertemp Target" and  a few seconds later the "Doeltempertuur". This does not happen.
On RMC is "Heat" selected., on water, and on outlet. No AI is used, and not on air

On the RMC the selected "Heat" temperature is 33, and "Disable Target setting" is off.

When I change the Stooklijn offset with 3, and later with -3 this is wat happens, no change in doeltemperatuur.
And as you see, when I setback teh Stooklijn offset to 0, because of dropping outside temperature the calculated stooklijn-temp has gone up +1 to 34 during this test, but doeltemperatuur stays on 33 all the time.

<img width="1230" alt="Scherm­afbeelding 2023-11-29 om 19 28 03" src="https://github.com/altrnate32/esp-lg-control/assets/9421474/fd2dd6d5-1887-4379-9a50-ee772b9d38c6">


Stupid question maybe, but I do see in the lg-heatpump-modbus.yaml file twice the same holding register 2. Is that not conflicting?

First in 269-281
 ```
- platform: modbus_controller
    modbus_controller_id: lg
    name: "Doeltemperatuur"
    id: doel_temp
    register_type: holding
    address: 2
    unit_of_measurement: "°C"
    value_type: U_WORD
    accuracy_decimals: 1
    skip_updates: 3
    filters:
      - multiply: 0.1
    icon: mdi:home-thermometer-outline
```

And later in 341-349:
```
number:
  - platform: modbus_controller
    modbus_controller_id: lg
    id: water_temp_target_output
    register_type: holding
    address: 2
    value_type: U_WORD
    step: 0.1
    multiply: 10
```

Hope it helps you!
