### ISSUE TITLE
help me my DS18B2 nowor

### ISSUE THREAD

**Issue by lozn00** [altrnate32/esp-lg-control#20]
- Scratch pad checksum invalid!
![image](https://github.com/fpovoski/ESP32-Temperature-Monitoring-PWM-Control-Board/assets/14260426/404cfcab-e751-4678-b83e-f426d557777b)
![image](https://github.com/fpovoski/ESP32-Temperature-Monitoring-PWM-Control-Board/assets/14260426/b0d61fd0-d324-4bd1-8fc4-915d005fc5bc)
```
dallas:
  - pin: GPIO27
    id: hub_1
sensor:
  - platform: debug
    free:
      name: "Heap Free"
  - platform: dallas
    address: 0x1C0000031EDD2A29
    name: "Room Temperature"
    id: temp1
    filters:
      - filter_out: NaN
      - offset: 0.0
      #- lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°C"
```
